### ISSUE TITLE
Buffer mapping inefficiency in OpenGL Backend

### ISSUE THREAD

**Issue by Admenri** [Admenri/urge#1]
OpenGL backend cost too much on buffer mapping I/O when drawcalls.
Consider a drawing method that can reduce io synchronization in rendering.

At the same time, improve the compatibility of opengl backend. :(

**Comment by Admenri** [comment]
Considering using WebGPU directly.

**Comment by daiaji** [comment]
https://github.com/mkxp-z/mkxp-z

OpenGL确实有点半死不活的老东西了。

上次搜索的时候，mkxp-z貌似把图形后端迁移到了vulkan。

不过游戏有额外的DLL的话，貌似就跑不了了。

偏偏用额外DLL的游戏很多，真要搞定得用WINE吧。

不过这又变成了为啥不直接`wine Game.exe`，就挺尴尬的。
